# Generated by Django 4.0.5 on 2022-06-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='Click in the link above to see the content', max_length=255),
        ),
    ]
